const MATCH_STATUS = {
  ACTIVE: "ACTIVE",
  JOINED: "JOINED",
  COMPLETED: "COMPLETED",
  DISPUTED: "DISPUTED",
  SETTLED: "SETTLED",
  CANCELLED: "CANCELLED",
  REJECTED: "REJECTED",
};

module.exports = { MATCH_STATUS };
