const TRANSACTION_TYPE = {
  ADD_MONEY: "ADD_MONEY",
  WITHDRAW: "WITHDRAW",
  WITHDRAW_REFUND: "WITHDRAW_REFUND",
  ADD_MONEY_REFUND: "ADD_MONEY_REFUND",
  GAME_CREATE: "GAME_CREATE",
  GAME_JOIN: "GAME_JOIN",
  GAME_WIN: "GAME_WIN",
  GAME_REFUND: "GAME_REFUND",
};

module.exports = { TRANSACTION_TYPE };
