const TRANSACTION_STATUS = {
  PENDING: "PENDING",
  INITIATED: "INITIATED",
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",
  CANCELLED: "CANCELLED",
  HOLD: "HOLD",
};

module.exports = { TRANSACTION_STATUS };
